modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Grass%20Seeds"
logoFile="icon.png"

[[mods]]
modId="grassseeds"
version="3.3"
displayName="Grass Seeds"
displayURL="https://serilum.com/mod/grass-seeds"
authors="Rick South"
description='''Allows the use of wheat seeds to transform dirt blocks to grass blocks and to create (tall) grass on them.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Alister, Andrean Olgo, aternosorg, Cherriesaurus, Michael W. S., Nahuel Fernandez, Shana Gitnick, Tyler Behl   

If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''

[[dependencies.grassseeds]]
    modId="collective"
    mandatory=true
    versionRange="[7.80,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.grassseeds]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21,1.21.1]"
    ordering="NONE"
    side="BOTH"
