modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Grass%20Seeds"
logoFile="icon.png"

[[mods]]
modId="grassseeds"
version="3.2"
displayName="Grass Seeds"
displayURL="https://serilum.com/mod/grass-seeds"
authors="Rick South"
description='''Allows the use of wheat seeds to transform dirt blocks to grass blocks and to create (tall) grass on them.
If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, FireStriker, Greg Johnson, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Shana Gitnick, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.grassseeds]]
    modId="collective"
    type="required"
    mandatory=true
    versionRange="[7.21,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.grassseeds]]
    modId="minecraft"
    type="required"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"